AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  promo-bot-mx

  Sample SAM Template for promo-bot-mx

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs12.x

Resources:
  GetHotPromos:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get-hot-promos/
      Handler: app.handler
      MemorySize: 1024
      Timeout: 6
      Role: arn:aws:iam::919590014828:role/LambdaExecutionDynamoDBRole
      Environment:
        Variables:
          TELEGRAM_URL: https://api.telegram.org/bot1342072847:AAEqGa6X5SPyudU1worL_UWkEvlqOHln0fY/sendMessage
          ENVIRONMENT: prod
          ENDPOINT: https://dynamodb.us-east-2.amazonaws.com
      Events:
        ExecuteEvery20Minutes:
          Type: Schedule
          Properties:
            Schedule: rate(20 minutes)
  DeleteHotPromos:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete-hot-promos/
      Handler: app.handler
      MemorySize: 128
      Timeout: 5
      Role: arn:aws:iam::919590014828:role/LambdaExecutionDynamoDBRole
      Environment:
        Variables:
          ENVIRONMENT: prod
          THRESHOLD_DAYS: 5
          ENDPOINT: https://dynamodb.us-east-2.amazonaws.com
      Events:
        ExecuteEveryDay:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
  PromosTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: 'N'
      TableName: promo_bot_mx_promos
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: created_at
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
Outputs:
  GetHotPromos:
    Description: "Lambda to get and save new Hot Promos"
    Value: !GetAtt GetHotPromos.Arn
